"""queue jobs

Revision ID: 42e407a1bb0c
Revises: dba04f81bede
Create Date: 2026-06-06 21:00:42.582321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42e407a1bb0c'
down_revision: Union[str, Sequence[str], None] = 'dba04f81bede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_column('events', 'location')
    op.add_column('events_employees', sa.Column('send_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=False)
    op.alter_column('folders', 'name',
               existing_type=sa.VARCHAR(length=300),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_folders_name'), 'folders', ['name'], unique=False)
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_index(op.f('ix_folders_name'), table_name='folders')
    op.alter_column('folders', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.drop_column('files', 'url')
    op.drop_column('events_employees', 'send_at')
    op.add_column('events', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
