"""media add is_direct_delete

Revision ID: 8758ffc85416
Revises: 76eda0f4361d
Create Date: 2026-06-29 17:03:52.929708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8758ffc85416"
down_revision: Union[str, Sequence[str], None] = "76eda0f4361d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("medias", sa.Column("is_direct_delete", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medias", "is_direct_delete")
    # ### end Alembic commands ###
