"""add status events - add overall_log queue_job

Revision ID: 9b581d297bb2
Revises: 8a059d80d8e3
Create Date: 2026-08-14 11:50:12.931094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b581d297bb2'
down_revision: Union[str, Sequence[str], None] = '8a059d80d8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('events_media_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'media_id')
    op.alter_column('medias', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('queue_job', sa.Column('overall_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_job', 'overall_log')
    op.alter_column('medias', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('events', sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_media_id_fkey'), 'events', 'medias', ['media_id'], ['id'])
    op.alter_column('events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
